A3/projectfile/qutickets/auth.py
from flask import Blueprint, flash, render_template, request, url_for, redirect
from werkzeug.security import generate_password_hash,check_password_hash
from .models import User
from .forms import LoginForm,RegisterForm
from flask_login import login_user, login_required,logout_user
from . import db
import re

# Create a blueprint - make sure all BPs have unique names
auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods = ['GET', 'POST'])
def login():
    login_form = LoginForm()
    if login_form.validate_on_submit():
        #get the username and password from the database
        user_name = login_form.user_name.data
        password = login_form.password.data
        user = db.session.scalar(db.select(User).where(User.name==user_name))
        error = None
        #if there is no user with that name
        if user is None:
            error = 'Incorrect username'#could be a security risk to give this much info away
        #check the password - notice password hash function
        elif not check_password_hash(user.password_hash, password): # takes the hash and password
            error = 'Incorrect password'
        if error is None:
            #all good, set the login_user of flask_login to manage the user
            login_user(user)
            print('Successfully logged in', 'Success')
            flash('You logged in successfully')
            return redirect(url_for('main.index'))
        else:
            flash(error)
    return render_template('user.html', form = login_form, heading = 'Login')

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    #the validation of form is fine, HTTP request is POST
    if (register.validate_on_submit()==True):
            #get username, password and email from the form
            uname = register.user_name.data
            pwd = register.password.data
            email = register.email_id.data
            contactNo = register.contactNo.data
            address=register.address.data
            #check if a user exists
            user = db.session.scalar(db.select(User).where(User.name==uname))
            if user:#this returns true when user is not None
                flash('Username already exists, please try another')
                return redirect(url_for('auth.register'))
            # don't store the password in plaintext!
            pwd_hash = generate_password_hash(pwd)
            #create a new User model object
            new_user = User(name=uname, password_hash=pwd_hash, emailid=email, contactNo=contactNo, address=address)
            db.session.add(new_user)
            db.session.commit()
            flash('You registered successfully')
            #commit to the database and redirect to HTML page
            return redirect(url_for('main.index'))
    #the else is called when the HTTP request calling this page is a GET
    else:
        return render_template('user.html', form=register, heading='Register')
    

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You logged out successfully')
    return redirect(url_for('main.index'))

A3/projectfile/qutickets/templates/base.html
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>QUTickets</title>    
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="/static/style/style.css" />
  </head>

  <body class="base-body">
    <!-- Header -->
    <header>
      <!-- Bootstrap Navbar -->
      <nav
        class="navbar navbar-expand-lg navbar-light bg-transparent custom-navbar"
      >
        <div class="container-fluid">
          <!-- Logo on the right -->
          <a class="navbar-logo" href="/">
            <img
              src="/static/img/QUtickets logo V1.png"
              alt="Logo"
              height="80"
            />
          </a>

        <!-- Login and Register buttons on the left -->
        <div class="d-flex">
          {% if current_user.is_authenticated %}
              <a class="btn btn-register btn-secondary" href="{{ url_for('event.profile') }}">Welcome {{ current_user.name }}</a>
              <a class="btn btn-register btn-secondary" href="{{ url_for('auth.logout') }}">Log Out</a>
          {% else %}
              <a class="btn btn-register btn-secondary" href="{{ url_for('auth.register') }}">Register</a>
              <a class="btn btn-register btn-secondary" href="{{ url_for('auth.login') }}">Log In</a>
          {% endif %}

          <a class="btn btn-register btn-secondary" href="{{ url_for('event.create') }}">Create Event</a>
        </div>
        </div>
      </nav>

      <!-- Code for using Flask flash -->
      <div class="container-fluid">
        {% with messages = get_flashed_messages() %} {% if messages %} {% for
        message in get_flashed_messages() %}
        <div class="alert alert-warning">
          <button
            type="button"
            class="close"
            data-dismiss="alert"
            aria-label="close"
          >
            x
          </button>
          {{message}}
        </div>
        {% endfor %} {% endif %} {% endwith %}
      </div>
      {% block header %} {% endblock %}
    </header>

    {% block content %} {% endblock %}

    <div>
    <footer class="footer">(C) Adrian Gadaleta, 2023. all rights reserved.</footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" 
    crossorigin="anonymous"></script>
  </div>
</body>

</html>

A3/projectfile/qutickets/templates/index.html
{% extends 'base.html' %}


<html>
        {% block header %}
        <div class="col">
          <iframe width="100%" height="450" style="border:0" loading="lazy" 
          allowfullscreen src="https://www.google.com/maps/embed/v1/search?q=live%20music%20near%20St%20Kilda%20VIC%2C%20Australia&key=AIzaSyATie1u0QbqTpOb1yfKS6tEDPG5ScYlNWg">
          </iframe> 
          {% endblock %}
          {% block content %}


          <div class="canvas">
            <div class="ttop">
              <!-- <div class="col" div id="custom-col"> -->
                <p>Discover<br />
                  /d&#618;&#712;sk&#652;v&#601;/</p>
                 
      
                 <p> verb: discover; <br />
                  1. find unexpectedly or during a search.<br />
                  2.<br />
                  archaic;<br />
                 Divulge (a secret).<br />
                 </p>
                <!-- </div> -->
            </div>
          </canvas>

          <div class="col" div id="custom-col-2">
            <form action = "" class= "form_search col-md-12" role="search" method = "POST">
              <input class= "searchInp" type="search" id="searchBar" name="searchBar"
              placeholder="Discover"
              aria-label="Search through site content">
              <button class = "searchbtn">
                <svg class= "svgSearch" viewBox="0 0 1024 1024"><path class="path1" d="M848.471 928l-263.059-263.059c-48.941 36.706-110.118 55.059-177.412 55.059-171.294 0-312-140.706-312-312s140.706-312 312-312c171.294 0 312 140.706 312 312 0 67.294-24.471 128.471-55.059 177.412l263.059 263.059-79.529 79.529zM189.623 408.078c0 121.364 97.091 218.455 218.455 218.455s218.455-97.091 218.455-218.455c0-121.364-103.159-218.455-218.455-218.455-121.364 0-218.455 97.091-218.455 218.455z"></path></svg>
              </button>
                </form>
          
            
        </div>
        </div>
        

        
         <!-- Create a row for the event cards -->
         <div class="row mt-4">
          <!-- Column 1 -->
          
          
          <div class="col-md-3">
            <h2>local</h2>
            {% for event in events %}
              {% if event.category == 'local'  %}             
              <a href="{{ url_for('event.show', id=event.id) }}"> <!-- Add link to event.show route -->  
                <div class="card">                
                  <img src="{{ event.eventImage }}" class="img img-responsive" alt="{{ event.name }}">                 
                      <div class="profile-name">{{ event.name }}</div>
                      <div class="profile-username">{{ event.venueName }}</div>
                      <div class="profile-date">{{ event.eventTime.strftime('%d %b, %Y') }}</div>
                      <div class="status">{{ event.status }}</div>                    
                </div>
              </a>
              {% endif %}
            {% endfor %}
          </div>         
          <!-- Column 2 -->
          <div class="col-md-3">            
            <h2>Imported</h2>
            {% for event in events %}
              {% if event.category == 'imported'  %}              
              <a href="{{ url_for('event.show', id=event.id) }}"> <!-- Add link to event.show route -->  
                <div class="card">                
                  <img src="{{ event.eventImage }}" class="img img-responsive" alt="{{ event.name }}">                  
                      <div class="profile-name">{{ event.name }}</div>
                      <div class="profile-username">{{ event.venueName }}</div>
                      <div class="profile-date">{{ event.eventTime.strftime('%d %b, %Y') }}</div>
                      <div class="status">{{ event.status }}</div>                    
                </div>
              </a>
              {% endif %}
            {% endfor %}
          </div>
          <!-- Column 3 -->
          <div class="col-md-3">            
            <h2>Emerging</h2>
            {% for event in events %}
              {% if event.category == 'emerging'  %}              
              <a href="{{ url_for('event.show', id=event.id) }}"> <!-- Add link to event.show route --> 
              <div class="card">                
                  <img src="{{ event.eventImage }}" class="img img-responsive" alt="{{ event.name }}">                                     
                      <div class="profile-name">{{ event.name }}</div>
                      <div class="profile-username">{{ event.venueName }}</div>
                      <div class="profile-date">{{ event.eventTime.strftime('%d %b, %Y') }}</div>
                      <div class="status">{{ event.status }}</div>                        
              </div>
            </a>
              {% endif %}
            {% endfor %}
          </div>
          <!-- Column 4 -->
          <div class="col-md-3">
            
            <h2>Impromptu</h2>
            {% for event in events %}
              {% if event.category == 'impromptu'  %}
              
              <a href="{{ url_for('event.show', id=event.id) }}"> <!-- Add link to event.show route --> 
                <div class="card">                 
                  <img src="{{ event.eventImage }}" class="img img-responsive" alt="{{ event.name }}">                  
                      <div class="profile-name">{{ event.name }}</div>
                      <div class="profile-username">{{ event.venueName }}</div>
                      <div class="profile-date">{{ event.eventTime.strftime('%d %b, %Y') }}</div>
                      <div class="status">{{ event.status }}</div>   
                </div>
              </a>
              {% endif %}
            {% endfor %}
          </div>
        </div>
    {% endblock %}

A3/projectfile/qutickets/templates/profilePage.html
{% extends 'base.html' %}


{% block content %}

      <main>
        <div class="col event-container-profile">
          <div class="row" style="max-width: fit-content;">
            <div class="col-md-12 custom-col-2">
              <h2>Your Bookings</h2> 




              <div class col-md-3> 
                <div class="col" id="profilediv" div id="custom-col-2">
                  <form action = "" class= "form_search col-md-12" role="search" method = "POST">
                    <input class= "searchInp" type="search" id="searchBar" name="searchBar"
                    placeholder="Discover"
                    aria-label="Search through site content">
                    <button class = "searchbtn">
                      <svg class= "svgSearch" viewBox="0 0 1024 1024"><path class="path1" d="M848.471 928l-263.059-263.059c-48.941 36.706-110.118 55.059-177.412 55.059-171.294 0-312-140.706-312-312s140.706-312 312-312c171.294 0 312 140.706 312 312 0 67.294-24.471 128.471-55.059 177.412l263.059 263.059-79.529 79.529zM189.623 408.078c0 121.364 97.091 218.455 218.455 218.455s218.455-97.091 218.455-218.455c0-121.364-103.159-218.455-218.455-218.455-121.364 0-218.455 97.091-218.455 218.455z"></path></svg>
                    </button>
                      </form>
  
              {% if booked_events != 0 %}
                <!-- Iterate through booked events using Jinja2 loop -->
                
                {% for booking in booked_events %}
                  <div class="card">
                    <img src="/{{ booking.event.eventImage }}" class="img img-responsive" alt="{{ booking.event.name }}">
                    <a href="{{ url_for('event.show', id=booking.event.id) }}">
                      <div class="profile-name">{{ booking.event.name }}</div>
                      <div class="profile-username">{{ booking.event.venueName }}</div>
                      <div class="profile-date">{{ booking.event.eventTime.strftime('%dth %B %Y') }}</div>
                      <div class="status">{{ booking.event.status }}</div>
                      
                    </a>
                  </div>
                  <h4>BOOKING ID: {{ booking.id }}</h4>
                  <h3>No. of tickets booked: {{ booking.num_tickets }}</h3>
                  <h5>Event booked @ {{ booking.purchase_date.strftime('%H:%M on %d/%m/%y') }}</h5>
                  
                {% endfor %}
                <!-- End of loop -->
              {% else %}
                <!-- Display a message when there are no bookings -->
                <p>No bookings yet. <a href="{{ url_for('event.index') }}">Browse events</a> to make a booking.</p>
              {% endif %}
            </div>
            </div>
          </div>
        </div>
      </main>
{% endblock %}

A3/projectfile/qutickets/templates/user.html
{% extends "base.html" %}
{% from "bootstrap5/form.html" import render_form %}
{% block content %}

<html>
<div class="page-header" style="display: flex; justify-content: left; align-items: left; padding-left: 25%; font-size: 20px; padding-top: 10%;">
  <h4>{{heading}}</h4>
</div>



<!-- Center the form using custom CSS class -->
<div class="centered-form-container">
  <div class="col-md-6">{{render_form(form)}}</div>
</div>

<!-- When you have a login form, show the user a styled link to register -->
{% if heading|lower =='login' %}
<div class="col-md-4">
  <p class="new-user-link">
    New user?
    <a href="{{ url_for('auth.register') }}" style="color: #007BFF; text-decoration: none;">Click here to register</a>.
  </p>
</div>
{% endif %}


<!-- Flashes any messages to the user -->
{% with messages = get_flashed_messages() %}
{% if messages %}
<!-- Check if there are any messages -->
<div class="container-fluid">
  <div class="row mt-3 mb-3">
    <div class="col-md-12">
      {% for message in messages %}
      <!-- Loop through the messages -->
      <div class="alert alert-info">{{message}}</div>
      <!-- Display as an alert -->
      {% endfor %}
    </div>
  </div>
</div>
{% endif %}
{% endwith %}
{% endblock %}
</html>